### PR TITLE
fix: check for non-empty accept header before performing accept header flow

### LINKED ISSUE #635: bug: 406 thrown for empty string accept header
Was doing benchmarks with autocannon and wrk and received 406s. this was due to the accept header being "" which made the request handler think it had to go through the accept header flow -- returning 406s.

Need to check for empty string before running through the accept header flow.

### PR DESCRIPTION
**Pull request by crookse**
Closes #635

Before:

```
Running 5s test @ http://localhost:1447?test=test
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   162.52ms  253.89ms   1.99s    92.58%
    Req/Sec   473.68     72.50   643.00     73.00%
  4796 requests in 5.09s, 2.54MB read
  Non-2xx or 3xx responses: 4796
Requests/sec:    941.74
Transfer/sec:    511.34KB
```

After:

```
Running 5s test @ http://localhost:1447?test=test
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.74ms    5.18ms 124.77ms   99.08%
    Req/Sec    14.80k     1.48k   15.78k    90.20%
  150207 requests in 5.10s, 19.63MB read
Requests/sec:  29431.85
Transfer/sec:      3.85MB
```

### CODE REVIEW

File: src/http/server.ts [hunk 1]
```diff
@@ -373,7 +373,7 @@ export class Server {
 
       const accept = request.headers.get("accept") ?? "";
       const contentType = response.headers.get("content-type") ?? "";
-      if (accept.includes("*/*") === false) {
+      if (accept && accept.trim() != "" && accept.includes("*/*") === false) {
```
Comment (Guergeiro) [inline src/http/server.ts:376]: God damn this conditions...

`accept` will always be defined because of line 374, therefore checking for it being defined is not required.

Also, `accept.trim()` should be compared with `!==` not `!=`.

Solutions for this condition may be:
```ts
// Solution 1
if (accept.trim() !== "" && accept.includes("*/*") === false) {
  // Stuff
}

// Solution 2
if (accept.trim().length !== 0 && accept.includes("*/*") === false) {
  // Stuff
}
```

**Review by Guergeiro — CHANGES_REQUESTED** [review]

File: src/http/server.ts (hunk 1 above)
Comment (crookse) [reply src/http/server.ts:376]: OHHHHH wow. i didn't see the `?? ""` part. that def changes things

**Comment by ebebbington** [comment]
Mad this changes the speed so much

File: src/http/server.ts (hunk 1 above)
Comment (crookse) [reply src/http/server.ts]: how's this @Guergeiro ? https://github.com/drashland/drash/pull/638/commits/95a419bdf5a60ecff892c9208a6092a27e8dd1d1

**Review by Guergeiro — APPROVED** [review]
Go go go!
